import turtle
a=turtle.Turtle()
turtle.bgcolor("black")
a.penup()
a.setposition(-10,-100)
a.pendown()
a.pensize(5)
a.begin_fill()
a.color("red")
a.pencolor("red")
a.left(130)
a.forward(150)
# a.right(40)
def heart():
    for i in range(100):
        a.right(2)
        a.forward(2)
heart()
a.right(220)
heart()
# a.right(43)
a.forward(150)
a.end_fill()
a.penup()
a.setpos(-40,10)
a.pendown()
a.pencolor("black")
a.write("Bhavya",font=("TimesNewRoman",20,"bold"))
turtle.done()
