import turtle
def circle(t):
    t.setposition(0,-300)
    t.pendown()
    t.begin_fill()
    t.color("pink")
    t.pencolor("white")
    t.circle(250)
    t.end_fill()
    t.penup()
def circle2(t):
    t.setposition(0,-250)
    t.pendown()
    t.begin_fill()
    t.circle(200)
    t.color("black")
    t.pencolor("white")
    t.end_fill()
    t.penup()
def draw_B(t):
    t.setposition(-20,-150)     
    t.pendown()
    t.begin_fill()
    t.color("red")
    t.pensize(10)
    t.pencolor("white")
    t.left(90)
    t.forward(170)
    t.left(120)
    t.forward(60)
    t.right(120)
    t.forward(40)
    t.right(60)
    t.forward(60)
    for i in range(190):
        t.forward(1)
        t.right(1)
    t.right(220)
    t.forward(10)
    for i in range(150):
        t.forward(1)
        t.right(1)
    t.forward(90)
    t.right(50)
    t.forward(30)
    t.right(120)
    t.forward(60)
    t.end_fill()
    t.penup()
    t.setpos(4,-70)
    t.pendown()
    t.begin_fill()
    t.color("black")
    t.pencolor("white")
    t.right(30)
    t.forward(10)
    for i in range(45):
        t.forward(1)
        t.right(1)
    t.right(40)
    t.forward(15)
    t.right(50)
    for i in range(50):
        t.forward(1)
        t.right(1)
    t.right(75)
    t.forward(140)
    t.right(70)
    for i in range(30):
        t.forward(1)
        t.right(1)
    t.right(40)
    t.forward(15)
    t.right(50)
    for i in range(55):
        t.forward(1)
        t.right(1)
    t.end_fill()
    t.penup()
    t.setpos(-6,70)
    t.pendown()
    t.begin_fill()
    t.color("yellow")
    t.pencolor("white")
    t.right(90)
    t.forward(50)
    t.right(140)
    t.forward(40)
    t.left(90)
    t.forward(35)
    t.right(140)
    t.forward(30)
    t.left(110)
    t.forward(35)
    t.right(140)
    t.forward(60)
    t.end_fill()

a=turtle.Screen()
a.bgcolor("black")

b=turtle.Turtle()
b.speed(10)
b.pensize(10)
b.penup()

circle(b)
circle2(b)
draw_B(b)

b.penup()

b.setposition(300,300)
b.pencolor("red")
b.write("Code by Dharsh")
b.hideturtle()
turtle.done()





