from tkinter import*
from tkinter import font,messagebox
from PIL import ImageTk, Image
import pymysql as mysql
   
def cust_regis(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f=Frame(root,height=1500,width=1500)
    f.pack()
    img=ImageTk.PhotoImage(Image.open('order.jpg'))
    l1=Label(f,image=img)
    l1.place(relx=0.0,rely=0.0)
    label_font=font.Font(weight="bold",family="Calibri",size=20)
    label=Label(root,text="CUSTOMER REGISTRATION",font=label_font,bg="blue",fg="white")
    label.place(relx=0.34,rely=0.1)
    l=Label(root,text="Name" ,fg="black",font=label_font,bg="pink")
    l.place(relx=0.3,rely=0.2)
    l1=Label(root,text="Email Id",fg="black",font=label_font,bg="pink")
    l1.place(relx=0.3,rely=0.3)
    l2=Label(root,text="Mobile No",fg="black",font=label_font,bg="pink")
    l2.place(relx=0.3,rely=0.4)
    l3=Label(root,text="Gender",fg="black",font=label_font,bg="pink")
    l3.place(relx=0.3,rely=0.5)
    l4=Label(root,text="Address",fg="black",font=label_font,bg="pink")
    l4.place(relx=0.3,rely=0.6)
    e=Entry(root)
    e.place(relx=0.5,rely=0.2,width=200,height=40)
    e1=Entry(root,)
    e1.place(relx=0.5,rely=0.3,width=200,height=40)
    e2=Entry(root)
    e2.place(relx=0.5,rely=0.4,width=200,height=40)
    e3=Entry(root)
    e3.place(relx=0.5,rely=0.5,width=200,height=40)
    e4=Entry(root)
    e4.place(relx=0.5,rely=0.6,width=200,height=40)

    
    def insert():
        connection=mysql.connect(host="localhost",user="root",password="livewire",database="shop")
        cursor=connection.cursor()
        s="insert into online1(name,emailid,mobileno,gender,address)values(%s,%s,%s,%s,%s)"
        t=(e.get(),e1.get(),e2.get(),e3.get(),e4.get())
        cursor.execute(s,t)
        connection.commit()
        messagebox.showinfo("registration","Insert successfully")
        
    def delete():
        connection=mysql.connect(host="localhost",user="root",password="livewire",database="shop")
        cursor=connection.cursor()
        sql="delete from online1 where name='"+e.get()+"'"
        cursor.execute(sql)
        connection.commit()
        messagebox.showinfo("delete successfully")

    def update():
        connection=mysql.connect(host="localhost",user="root",password="livewire",database="shop")
        cursor=connection.cursor()
        sql="update online1 set emailid='"+str(e1.get())+"',mobileno ='"+str(e2.get())+"',gender='"+str(e3.get())+"',address='"+str(e4.get())+"'where name='"+str(e.get())+"'"
        cursor.execute(sql)
        connection.commit()
        messagebox.showinfo("update successfully")

    
    btn1=Button(root,text="insert",bg="violet",fg="white",font=label_font,command=lambda:insert())
    btn1.place(relx=0.7,rely=0.2)
    btn2=Button(root,text="delete",bg="violet",fg="white",font=label_font,command=lambda:delete())
    btn2.place(relx=0.7,rely=0.3)
    btn3=Button(root,text="update",bg="violet",fg="white",font=label_font,command=lambda:update())
    btn3.place(relx=0.7,rely=0.4)
    
   
    # def online(root):
    #     f=open('online.txt','a')
    #     f.write(str(e.get()))
    #     f.write("\n")
    #     f.write(str(e1.get()))
    #     f.write("\t")
    #     f.write(str(e2.get()))
    #     f.write("\t")
    #     f.write(str(e3.get()))
    #     f.write("\t")
    #     f.write(str(e4.get()))
    #     f.write("\n")
    b=Button(root,text="REGISTER",font=label_font,bg="green",fg="white")
    b.place(relx=0.42,rely=0.75)    
    root.mainloop()  


def start(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f=Frame(root,height=1500,width=1500,bg="pink")
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)
    f1=Frame(root,height=50,width=1500,bg="purple")
    label_font1=font.Font(weight="bold",family="Times New Roman",size=16)
    l=Label(f1,text="** OFFERS SALE **",fg="yellow",font=label_font,bg="purple")
    l.place(relx=0.17,rely=0.1)
    l2=Label(f1,text="** BEST QUALITY SHOPPING **",fg="yellow",font=label_font,bg="purple")
    l2.place(relx=0.65,rely=0.1)
    f1.pack()

    f2=Frame(root,height=1455,width=750)
    img1=ImageTk.PhotoImage(Image.open('offer4.jpg'))
    l3=Label(f2,image=img1)
    l3.place(relx=0.0,rely=0.0)
    img2=ImageTk.PhotoImage(Image.open('offer5.jpg'))
    l4=Label(f2,image=img2)
    l4.place(relx=0.5,rely=0.0)
    img3=ImageTk.PhotoImage(Image.open('offer6.jpg'))
    l5=Label(f2,image=img3)
    l5.place(relx=0.00,rely=0.27)
    img4=ImageTk.PhotoImage(Image.open('offer8.jpg'))
    l6=Label(f2,image=img4)
    l6.place(relx=0.5,rely=0.27)
    f2.place(relx=0.0,rely=0.068)

    f3=Frame(root,height=1455,width=750,bg="pink")
    img5=ImageTk.PhotoImage(Image.open('kurtii.jpg'))
    l7=Label(f3,image=img5)
    l7.place(relx=0.1,rely=0.01)
    img6=ImageTk.PhotoImage(Image.open('menn.jpg'))
    l8=Label(f3,image=img6)
    l8.place(relx=0.5,rely=0.01)
    img7=ImageTk.PhotoImage(Image.open('kid.jpg'))
    l9=Label(f3,image=img7)
    l9.place(relx=0.15,rely=0.24)
    img8=ImageTk.PhotoImage(Image.open('cookware.jpg'))
    l10=Label(f3,image=img8)
    l10.place(relx=0.46,rely=0.24)
    b1=Button(f3,text="Womens's & Men's Store",bg="purple",fg="yellow",font=label_font1,command=lambda:women_men_store(root))
    b1.place(relx=0.27,rely=0.2)
    b2=Button(f3,text="Kid's & Home's Store",bg="purple",fg="yellow",font=label_font1,command=lambda:home_kid_store(root))
    b2.place(relx=0.29,rely=0.44)
    b3=Button(f3,text="Back",bg="purple",fg="yellow",font=label_font,command=lambda:home())
    b3.place(relx=0.25,rely=0.9)
    f3.place(relx=0.5,rely=0.068)
    f.pack()
    root.mainloop(root)

    



   
def cust_login(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f=Frame(root,height=1500,width=1500)
   
    img=ImageTk.PhotoImage(Image.open('onlineshop4.jpg'))
    l=Label(f,image=img)
    l.place(relx=0.0,rely=0.0)
    label_font=font.Font(weight="bold",family="Calibri",size=20)
    label=Label(root,text="CUTOMER LOGIN",font=label_font,bg="green",fg="white")
    label.place(relx=0.42,rely=0.1)
    l=Label(root,text="User Name",fg="black",font=label_font,bg="pink")
    l.place(relx=0.33,rely=0.3)
    l1=Label(root,text="Password",fg="black",font=label_font,bg="pink")
    l1.place(relx=0.33,rely=0.5)
    e=Entry(root)
    e.place(relx=0.5,rely=0.3,width=200,height=40)
    e1=Entry(root)
    e1.place(relx=0.5,rely=0.5,width=200,height=40)
    a=Entry(root,show="*")
    a.place(relx=0.5,rely=0.5,width=200,height=40)
    f.pack()


    
    def cust_login1(root):
        m1=e.get()
        n1=a.get()
        f=open("online.txt","r")
        time=f.read()
        lines=time.split("\n")
        for line in lines:
            info=line.split()
            if info[0]==m1 and info[1]==n1:
                print("login")
                messagebox.showinfo("Login","login successfully")
                start(root)

                def info():
                    info=open("online.txt","a")
                    info=info.read()
                info()

                
                break
            else:
                print("invaild")
                messagebox.showerror("Error","invaild")
                break
    b=Button(root,text="LOGIN",font=label_font,bg="green",fg="white",command=lambda:cust_login1(root))
    b.place(relx=0.46,rely=0.7)   
    root.mainloop()


def kurtis(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="purple")
    label_font=font.Font(weight="bold",family="calibri",size=12) 
    img8=ImageTk.PhotoImage(Image.open('background.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.0)
    f2=Frame(root,height=710,width=1000,bg="skyblue")
    f2.place(relx=0.15,rely=0.05)
    label_fontt=font.Font(weight="bold",family="calibri",size=25) 
    label=Label(f2,text="KURTISS COLLECTION",bg="skyblue",fg="black",font=label_fontt)
    label.place(relx=0.34,rely=0.05)  
    img=ImageTk.PhotoImage(Image.open('kurths4.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.13,rely=0.15)
    b=Button(root,text="kurta sets",fg="black",bg="pink",font=label_font,command=lambda:kurtis1(root))
    b.place(relx=0.26,rely=0.46)
   
    img1=ImageTk.PhotoImage(Image.open('kurths5.jpg'))
    l2=Label(f2,image=img1)
    l2.place(relx=0.33,rely=0.15)
    b1=Button(root,text="Tops",fg="black",bg="pink",font=label_font)
    b1.place(relx=0.57,rely=0.46)
    
    img2=ImageTk.PhotoImage(Image.open('kurths6.jpg'))
    l3=Label(f2,image=img2)
    l3.place(relx=0.54,rely=0.15)
    b2=Button(root,text="fashion kurta",fg="black",bg="pink",font=label_font)
    b2.place(relx=0.41,rely=0.46)
    
    img3=ImageTk.PhotoImage(Image.open('kurths7.jpg'))
    l4=Label(f2,image=img3)
    l4.place(relx=0.73,rely=0.15)
    b3=Button(root,text="kurti",fg="black",bg="pink",font=label_font)
    b3.place(relx=0.72,rely=0.46)
   

    img4=ImageTk.PhotoImage(Image.open('kurths8.jpg'))
    l5=Label(f2,image=img4)
    l5.place(relx=0.13,rely=0.6)
    b4=Button(root,text="plazzo sets",fg="black",bg="pink",font=label_font)
    b4.place(relx=0.26,rely=0.87)
    

    img5=ImageTk.PhotoImage(Image.open('kurti1.jpg'))
    l6=Label(f2,image=img5)
    l6.place(relx=0.33,rely=0.6)
    b5=Button(root,text="long tops",fg="black",bg="pink",font=label_font)
    b5.place(relx=0.56,rely=0.87)
    

    img6=ImageTk.PhotoImage(Image.open('ethnic2.jpg'))
    l6=Label(f2,image=img6)
    l6.place(relx=0.53,rely=0.6)
    b6=Button(root,text="set sudi",fg="black",bg="pink",font=label_font)
    b6.place(relx=0.41,rely=0.87)


    img7=ImageTk.PhotoImage(Image.open('ethtnic1.jpg'))
    l6=Label(f2,image=img7)
    l6.place(relx=0.73,rely=0.6)
    b7=Button(root,text="women kurti",fg="black",bg="pink",font=label_font)
    b7.place(relx=0.7,rely=0.87)
    label_font1=font.Font(weight="bold",family="calibri",size=17)
    lbl1=Label(root,text="Rs.250",fg="black",bg="skyblue",font=label_font1)
    lbl1.place(relx=0.26,rely=0.51)
    lbl2=Label(root,text="Rs.300",fg="black",bg="skyblue",font=label_font1)
    lbl2.place(relx=0.41,rely=0.51)
    lbl3=Label(root,text="Rs.350",fg="black",bg="skyblue",font=label_font1)
    lbl3.place(relx=0.71,rely=0.51)
    lbl4=Label(root,text="Rs.450",fg="black",bg="skyblue",font=label_font1)
    lbl4.place(relx=0.56,rely=0.92)
    lbl5=Label(root,text="Rs.500",fg="black",bg="skyblue",font=label_font1)
    lbl5.place(relx=0.26,rely=0.92)
    lbl6=Label(root,text="Rs.570",fg="black",bg="skyblue",font=label_font1)
    lbl6.place(relx=0.41,rely=0.92)
    lbl7=Label(root,text="Rs.650",fg="black",bg="skyblue",font=label_font1)
    lbl7.place(relx=0.55,rely=0.51)
    lbl8=Label(root,text="Rs.700",fg="black",bg="skyblue",font=label_font1)
    lbl8.place(relx=0.71,rely=0.92)
    f1.pack()   
    root.mainloop()
          
def menfoot(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    img8=ImageTk.PhotoImage(Image.open('background5.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.0)

    f2=Frame(root,height=700,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label=Label(f2,text=" Trendy Black Shoes",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.1)
    label=Label(f2,text="Rs.1000",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.2)
    label_font1=font.Font(weight="bold",family="Times New Roman",size=21)
    label=Label(f2,text="Product details",bg="pink",fg="purple",font=label_font1)
    label.place(relx=0.5,rely=0.3)
    label=Label(f2,text="Name: Black Shoes ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.4)
    label=Label(f2,text="Fabric: Leather",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.5)
    label=Label(f2,text="Select Size:",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.6)
    label_font2=font.Font(weight="bold",family="Times New Roman",size=18) 
    b=Button(root,text="8",fg="black",bg="white",font=label_font2)
    b.place(relx=0.55,rely=0.67)   
    b=Button(root,text="9",fg="black",bg="white",font=label_font2)
    b.place(relx=0.65,rely=0.67)


    
    b=Button(root,text="10",fg="black",bg="white",font=label_font2)
    b.place(relx=0.75,rely=0.67)
    label=Label(f2,text="Pattern: Stylish",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.79)
    label=Label(f2,text="Net Quantity(N): 1",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.89)
    img=ImageTk.PhotoImage(Image.open('mfoot.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.05,rely=0.13)


    b=Button(root,text="Add to Cart",fg="black",bg="white",font=label_font,command=lambda:cart(root))
    b.place(relx=0.17,rely=0.77)
    b1=Button(root,text="Buy Now",fg="white",bg="purple",font=label_font,command=lambda:order(root))
    b1.place(relx=0.33,rely=0.77)

    f1.pack()
    root.mainloop()
          
def menaccess(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    img8=ImageTk.PhotoImage(Image.open('background5.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.0)

    f2=Frame(root,height=710,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label=Label(f2,text="Silver Watch",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.1)
    label=Label(f2,text="Rs.1300",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.2)
    label_font1=font.Font(weight="bold",family="Times New Roman",size=21)
    label=Label(f2,text="Product details",bg="pink",fg="purple",font=label_font1)
    label.place(relx=0.5,rely=0.3)
    label=Label(f2,text="Name: Trendy Watch ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.4)
    label=Label(f2,text="Metal: Silver",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.5)
    label=Label(f2,text="Free Size",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.6)
    
    
    label=Label(f2,text="Pattern: Stylish",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.7)
    label=Label(f2,text="Net Quantity(N): 1",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.8)
    img=ImageTk.PhotoImage(Image.open('mwatch.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.05,rely=0.13)


    b=Button(root,text="Add to Cart",fg="black",bg="white",font=label_font,command=lambda:cart(root))
    b.place(relx=0.17,rely=0.77)
    b1=Button(root,text="Buy Now",fg="white",bg="purple",font=label_font,command=lambda:order(root))
    b1.place(relx=0.33,rely=0.77)

    f1.pack()
    root.mainloop()
        
        
       
def menbottom(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    img8=ImageTk.PhotoImage(Image.open('background5.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.0)

    f2=Frame(root,height=710,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label=Label(f2,text="Jeans Pants",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.1)
    label=Label(f2,text="Rs.1300",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.2)
    label_font1=font.Font(weight="bold",family="Times New Roman",size=21)
    label=Label(f2,text="Product details",bg="pink",fg="purple",font=label_font1)
    label.place(relx=0.5,rely=0.3)
    label=Label(f2,text="Name: Trendy Jeans Pant ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.4)
    label=Label(f2,text="Fabric: Jeans",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.5)
    label=Label(f2,text="Select Size:",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.6)
    
    label_font2=font.Font(weight="bold",family="Times New Roman",size=18) 
    b=Button(root,text="32",fg="black",bg="white",font=label_font2)
    b.place(relx=0.55,rely=0.69)    
    b=Button(root,text="34",fg="black",bg="white",font=label_font2)
    b.place(relx=0.65,rely=0.69)    
    b=Button(root,text="36",fg="black",bg="white",font=label_font2)
    b.place(relx=0.75,rely=0.69)
    label=Label(f2,text="Pattern: Stylish",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.79)
    label=Label(f2,text="Net Quantity(N): 1",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.89)
    img=ImageTk.PhotoImage(Image.open('mbottom.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.05,rely=0.13)


    b=Button(root,text="Add to Cart",fg="black",bg="white",font=label_font,command=lambda:cart(root))
    b.place(relx=0.17,rely=0.77)
    b1=Button(root,text="Buy Now",fg="white",bg="purple",font=label_font,command=lambda:order(root))
    b1.place(relx=0.33,rely=0.77)
    f1.pack()
    root.mainloop()
        
    
def mentop(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    img8=ImageTk.PhotoImage(Image.open('background5.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.0)

    f2=Frame(root,height=710,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label=Label(f2,text="Men Shirt",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.1)
    label=Label(f2,text="Rs.1700",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.2)
    label_font1=font.Font(weight="bold",family="Times New Roman",size=21)
    label=Label(f2,text="Product details",bg="pink",fg="purple",font=label_font1)
    label.place(relx=0.5,rely=0.3)
    label=Label(f2,text="Name: Formal Shirt ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.4)
    label=Label(f2,text="Fabric: Cotton",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.5)
    label=Label(f2,text="Select Size:",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.6)
   
    label_font2=font.Font(weight="bold",family="Times New Roman",size=18) 
    b=Button(root,text="30",fg="black",bg="white",font=label_font2)
    b.place(relx=0.55,rely=0.69)  
    b=Button(root,text="32",fg="black",bg="white",font=label_font2)
    b.place(relx=0.65,rely=0.69)   
    b=Button(root,text="34",fg="black",bg="white",font=label_font2)
    b.place(relx=0.75,rely=0.69)
    label=Label(f2,text="Pattern: Formal",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.79)
    label=Label(f2,text="Net Quantity(N): 1",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.89)
    img=ImageTk.PhotoImage(Image.open('mtop.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.07,rely=0.13)

    b=Button(root,text="Add to Cart",fg="black",bg="white",font=label_font,command=lambda:cart(root))
    b.place(relx=0.17,rely=0.77)
    b1=Button(root,text="Buy Now",fg="white",bg="purple",font=label_font,command=lambda:order(root))
    b1.place(relx=0.33,rely=0.77)
    f1.pack()
    root.mainloop()

def order(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500)
    img=ImageTk.PhotoImage(Image.open('order1.jpg'))
    l1=Label(f1,image=img)
    l1.place(relx=0.00,rely=0.00)
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    label=Label(f1,text="phone no:",font=label_font,bg="pink",fg="black")
    label.place(relx=0.28,rely=0.4)
    entry=Entry(f1)
    entry.place(relx=0.52,rely=0.4,width=150,height=40)

    def phone(root):
        if (entry.get()==''):
            messagebox.showwarning("Error","please check your no")
        else:
            messagebox.showinfo("msg","continue to order")
            delivery(root)

    button=Button(f1,text="continue",font=label_font,bg="purple",fg="white",command=lambda:phone(root))
    button.place(relx=0.4,rely=0.68)
    f1.pack()
    root.mainloop()

def delivery(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500)
    img=ImageTk.PhotoImage(Image.open('onlineshop.jpg'))
    l=Label(f1,image=img)
    l.place(relx=0.0,rely=0.0)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20)  
    label=Label(root,text="ORDER PLACE DETAILS",font=label_font,bg="blue",fg="white")
    label.place(relx=0.4,rely=0.1)
    l1=Label(root,text="Name:",font=label_font,bg="pink",fg="black")
    l1.place(relx=0.3,rely=0.2)
    l2=Label(root,text="Mobile No:",font=label_font,bg="pink",fg="black")
    l2.place(relx=0.3,rely=0.3)
    l3=Label(root,text="Address:",font=label_font,bg="pink",fg="black")
    l3.place(relx=0.3,rely=0.4)
    l4=Label(root,text="Payment Mode:",font=label_font,bg="pink",fg="black")
    l4.place(relx=0.3,rely=0.5)

    b1=Button(root,text="Order Confirmed",font=label_font,bg="purple",fg="yellow")
    b1.place(relx=0.3,rely=0.6)
    b1=Button(root,text="Order Cancelled",font=label_font,bg="purple",fg="yellow")
    b1.place(relx=0.5,rely=0.6)
    e=Entry(root)
    e.place(relx=0.5,rely=0.2,width=200,height=40)
    e1=Entry(root,)
    e1.place(relx=0.5,rely=0.3,width=200,height=40)
    e2=Entry(root)
    e2.place(relx=0.5,rely=0.4,width=200,height=40)
    e3=Entry(root)
    e3.place(relx=0.5,rely=0.5,width=200,height=40)

    
    def insert_order_confirmed():
        connection=mysql.connect(host="localhost",user="root",password="livewire",database="delivery")
        cursor=connection.cursor()
        s="insert into order1(name,mobileno,address,paymentmode)values(%s,%s,%s,%s)"
        t=(e.get(),e1.get(),e2.get(),e3.get())
        cursor.execute(s,t)
        connection.commit()
        messagebox.showinfo("registration","Your order confirmed")
    
    def cancel():
        connection=mysql.connect(host="localhost",user="root",password="livewire",database="delivery")
        cursor=connection.cursor()
        sql="delete from order1 where name='"+e.get()+"'"
        cursor.execute(sql)
        connection.commit()
        messagebox.showinfo("cancel successfully")
   

    b1=Button(root,text="Order Confirmed",font=label_font,bg="purple",fg="yellow",command=lambda:insert_order_confirmed())
    b1.place(relx=0.3,rely=0.6)
    b1=Button(root,text="Order Cancelled",font=label_font,bg="purple",fg="yellow",command=lambda:cancel())
    b1.place(relx=0.5,rely=0.6)
    f1.pack()
    b1=Button(root,text="Close",font=label_font,bg="purple",fg="yellow",command=lambda:exit())
    b1.place(relx=0.75,rely=0.8)
    root.mainloop()
    
def cart(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500)
    img=ImageTk.PhotoImage(Image.open('onlineshop3.jpg'))
    l1=Label(f1,image=img)
    l1.place(relx=0.0,rely=0.00)
    label_font=font.Font(weight="bold",family="Times New Roman",size=20) 
    img1=ImageTk.PhotoImage(Image.open('cartimage.jpg'))
    l2=Label(f1,image=img1)
    l2.place(relx=0.1,rely=0.2)
    label=Label(f1,text="Women modern kurti",font=label_font,bg="pink",fg="black")
    label.place(relx=0.3,rely=0.2)
    label1=Label(f1,text="Size:XL",font=label_font,bg="orange",fg="black")
    label1.place(relx=0.3,rely=0.3)
    label2=Label(f1,text="Color:Green",font=label_font,bg="orange",fg="black")
    label2.place(relx=0.3,rely=0.4)
    button=Button(f1,text="Close",font=label_font,bg="purple",fg="white",command=lambda:exit())
    button.place(relx=0.7,rely=0.8)
    f1.place(relx=0.2,rely=0.5)
    f1.pack()
    root.mainloop()

def womenfoot(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    img8=ImageTk.PhotoImage(Image.open('background5.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.0)

    f2=Frame(root,height=710,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label=Label(f2,text="White Sandals",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.15)
    label=Label(f2,text="Rs.700",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.25)
    label_font1=font.Font(weight="bold",family="Times New Roman",size=21)
    label=Label(f2,text="Product details",bg="pink",fg="purple",font=label_font1)
    label.place(relx=0.5,rely=0.35)
    label=Label(f2,text="Name: Women Sandals ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.45)
    label=Label(f2,text="Fabric: Leather",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.55)
    label=Label(f2,text="Select Size:",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.65)
    
    label_font2=font.Font(weight="bold",family="Times New Roman",size=18) 
    b=Button(root,text="8",fg="black",bg="white",font=label_font2)
    b.place(relx=0.55,rely=0.7)
    
    b=Button(root,text="9",fg="black",bg="white",font=label_font2)
    b.place(relx=0.65,rely=0.7)
    
    b=Button(root,text="10",fg="black",bg="white",font=label_font2)
    b.place(relx=0.75,rely=0.7)
    label=Label(f2,text="Pattern: War Type ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.8)
    label=Label(f2,text="Net Quantity(N): 1",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.9)
    img=ImageTk.PhotoImage(Image.open('wfoot1.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.05,rely=0.15)


    b=Button(root,text="Add to Cart",fg="black",bg="white",font=label_font,command=lambda:cart(root))
    b.place(relx=0.17,rely=0.77)
    b1=Button(root,text="Buy Now",fg="white",bg="purple",font=label_font,command=lambda:order(root))
    b1.place(relx=0.33,rely=0.77)
    f1.pack()
    root.mainloop()

def womenaccess(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    img8=ImageTk.PhotoImage(Image.open('background5.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.0)

    f2=Frame(root,height=710,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label=Label(f2,text="Lakshmi Jewel sets",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.15)
    label=Label(f2,text="Rs.700",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.25)
    label_font1=font.Font(weight="bold",family="Times New Roman",size=21)
    label=Label(f2,text="Product details",bg="pink",fg="purple",font=label_font1)
    label.place(relx=0.5,rely=0.35)
    label=Label(f2,text="Name: Women Accessories ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.45)
    label=Label(f2,text="Metal: Gold Plated ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.55)
    label=Label(f2,text="Free Size",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.65)
    label=Label(f2,text="Pattern: Stone Work ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.75)
    label=Label(f2,text="Net Quantity(N): 1",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.85)
    img=ImageTk.PhotoImage(Image.open('waccess1.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.05,rely=0.17)


    b=Button(root,text="Add to Cart",fg="black",bg="white",font=label_font,command=lambda:cart(root))
    b.place(relx=0.17,rely=0.77)
    b1=Button(root,text="Buy Now",fg="white",bg="purple",font=label_font,command=lambda:order(root))
    b1.place(relx=0.33,rely=0.77)
    f1.pack()
    root.mainloop()

def kurtis1(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="black")
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    img8=ImageTk.PhotoImage(Image.open('background5.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.00)
    f2=Frame(root,height=700,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label=Label(f2,text="Modern Kurti",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.1)
    label=Label(f2,text="Rs.1500",bg="pink",fg="green",font=label_font)
    label.place(relx=0.5,rely=0.2)
    label_font1=font.Font(weight="bold",family="Times New Roman",size=21)
    label=Label(f2,text="Product details",bg="pink",fg="purple",font=label_font1)
    label.place(relx=0.5,rely=0.3)
    label=Label(f2,text="Name: Modern Kurti ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.4)
    label=Label(f2,text="Fabric: Rayon",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.5)
    label=Label(f2,text="Select Size:",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.6)
   
    label_font2=font.Font(weight="bold",family="Times New Roman",size=18) 
    b=Button(root,text="M",fg="black",bg="white",font=label_font2)
    b.place(relx=0.55,rely=0.69)
    
    b=Button(root,text="XL",fg="black",bg="white",font=label_font2)
    b.place(relx=0.65,rely=0.69)
    
    b=Button(root,text="L",fg="black",bg="white",font=label_font2)
    b.place(relx=0.75,rely=0.69)
    label=Label(f2,text="Pattern: Printed ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.79)
    label=Label(f2,text="Net Quantity(N): 1",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.5,rely=0.89)
    img=ImageTk.PhotoImage(Image.open('kurthi1.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.05,rely=0.13)


    b=Button(root,text="Add to Cart",fg="black",bg="white",font=label_font,command=lambda:cart(root))
    b.place(relx=0.17,rely=0.77)
    b1=Button(root,text="Buy Now",fg="white",bg="purple",font=label_font,command=lambda:order(root))
    b1.place(relx=0.33,rely=0.77)

    f1.pack()
    root.mainloop()
def saree1(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=25) 
    img8=ImageTk.PhotoImage(Image.open('background5.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.00)

    f2=Frame(root,height=700,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label=Label(f2,text="Silk Saree",bg="pink",fg="green",font=label_font)
    label.place(relx=0.6,rely=0.1)
    label=Label(f2,text="Rs.1500",bg="pink",fg="green",font=label_font)
    label.place(relx=0.6,rely=0.2)
    label_font1=font.Font(weight="bold",family="Times New Roman",size=21)
    label=Label(f2,text="Product details",bg="pink",fg="purple",font=label_font1)
    label.place(relx=0.6,rely=0.3)
    label=Label(f2,text="Name: Silk Saree ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.6,rely=0.4)
    label=Label(f2,text="Fabric: Silk",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.6,rely=0.5)
    label=Label(f2,text="Free Size",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.6,rely=0.6)
    label=Label(f2,text="Pattern: Designing ",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.6,rely=0.7)
    label=Label(f2,text="Net Quantity(N): 1",bg="pink",fg="black",font=label_font1)
    label.place(relx=0.6,rely=0.8)
    img=ImageTk.PhotoImage(Image.open('cottonsaree.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.05,rely=0.13)


    b=Button(root,text="Add to Cart",fg="black",bg="white",font=label_font,command=lambda:(root))
    b.place(relx=0.2,rely=0.77)
    b1=Button(root,text="Buy Now",fg="white",bg="purple",font=label_font,command=lambda:order(root))
    b1.place(relx=0.4,rely=0.77)

    f1.pack()
    root.mainloop()
def sarees(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="purple")
    img8=ImageTk.PhotoImage(Image.open('background.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.00)
    label_font=font.Font(weight="bold",family="Times New Roman",size=12) 
    f2=Frame(root,height=710,width=1000,bg="skyblue")

    f2.place(relx=0.15,rely=0.05)
    label_fontt=font.Font(weight="bold",family="calibri",size=25) 
    label=Label(f2,text="SAREES COLLECTION",bg="skyblue",fg="black",font=label_fontt)
    label.place(relx=0.35,rely=0.05)    
    img=ImageTk.PhotoImage(Image.open('saree1.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.13,rely=0.15)
    img1=ImageTk.PhotoImage(Image.open('saree2.jpg'))
    l2=Label(f2,image=img1)
    l2.place(relx=0.33,rely=0.15)
    img2=ImageTk.PhotoImage(Image.open('saree3.jpg'))
    l3=Label(f2,image=img2)
    l3.place(relx=0.54,rely=0.15)
    img3=ImageTk.PhotoImage(Image.open('saree6.jpg'))
    l4=Label(f2,image=img3)
    l4.place(relx=0.73,rely=0.15)
    img4=ImageTk.PhotoImage(Image.open('saree5.jpg'))
    l5=Label(f2,image=img4)
    l5.place(relx=0.13,rely=0.6)
    img5=ImageTk.PhotoImage(Image.open('saree7.jpg'))
    l6=Label(f2,image=img5)
    l6.place(relx=0.33,rely=0.6)
    img6=ImageTk.PhotoImage(Image.open('saree8.jpg'))
    l6=Label(f2,image=img6)
    l6.place(relx=0.53,rely=0.6)
    img7=ImageTk.PhotoImage(Image.open('saree9.jpg'))
    l6=Label(f2,image=img7)
    l6.place(relx=0.73,rely=0.6)

    b=Button(root,text="cotton saree",fg="black",bg="pink",font=label_font,command=lambda:saree1(root))
    b.place(relx=0.26,rely=0.46)

    b1=Button(root,text="Banarasi silk",fg="black",bg="pink",font=label_font)
    b1.place(relx=0.55,rely=0.46)

    b2=Button(root,text="silk saree",fg="black",bg="pink",font=label_font)
    b2.place(relx=0.41,rely=0.46)

    b3=Button(root,text="soft silk",fg="black",bg="pink",font=label_font)
    b3.place(relx=0.7,rely=0.46)

    b4=Button(root,text="Mysor saree",fg="black",bg="pink",font=label_font)
    b4.place(relx=0.26,rely=0.87)
    
    b5=Button(root,text="shiffon saree",fg="black",bg="pink",font=label_font)
    b5.place(relx=0.56,rely=0.87)
    
    b6=Button(root,text="printed saree",fg="black",bg="pink",font=label_font)
    b6.place(relx=0.41,rely=0.87)
    b7=Button(root,text="kubera pattu",fg="black",bg="pink",font=label_font)
    b7.place(relx=0.7,rely=0.87)
    label_font1=font.Font(weight="bold",family="calibri",size=17)
    lbl1=Label(root,text="Rs.250",fg="black",bg="skyblue",font=label_font1)
    lbl1.place(relx=0.26,rely=0.51)
    lbl2=Label(root,text="Rs.300",fg="black",bg="skyblue",font=label_font1)
    lbl2.place(relx=0.41,rely=0.51)
    lbl3=Label(root,text="Rs.350",fg="black",bg="skyblue",font=label_font1)
    lbl3.place(relx=0.71,rely=0.51)
    lbl4=Label(root,text="Rs.450",fg="black",bg="skyblue",font=label_font1)
    lbl4.place(relx=0.56,rely=0.92)
    lbl5=Label(root,text="Rs.500",fg="black",bg="skyblue",font=label_font1)
    lbl5.place(relx=0.26,rely=0.92)
    lbl6=Label(root,text="Rs.570",fg="black",bg="skyblue",font=label_font1)
    lbl6.place(relx=0.41,rely=0.92)
    lbl7=Label(root,text="Rs.650",fg="black",bg="skyblue",font=label_font1)
    lbl7.place(relx=0.57,rely=0.51)
    lbl8=Label(root,text="Rs.700",fg="black",bg="skyblue",font=label_font1)
    lbl8.place(relx=0.71,rely=0.92)


    
    f1.pack()
    
    root.mainloop()

def women_foot(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=12) 
    img8=ImageTk.PhotoImage(Image.open('background.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.00)
    f2=Frame(root,height=720,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label_fontt=font.Font(weight="bold",family="calibri",size=25) 
    label=Label(f2,text="WOMEN'S FOOT WEARS",bg="pink",fg="black",font=label_fontt)
    label.place(relx=0.35,rely=0.05)      
    img=ImageTk.PhotoImage(Image.open('womenfoot9.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.08,rely=0.15)
    img1=ImageTk.PhotoImage(Image.open('womenfoot2.jpg'))
    l2=Label(f2,image=img1)
    l2.place(relx=0.31,rely=0.15)
    img2=ImageTk.PhotoImage(Image.open('womenfoot3.jpg'))
    l3=Label(f2,image=img2)
    l3.place(relx=0.53,rely=0.15)
    img3=ImageTk.PhotoImage(Image.open('womenfoot4.jpg'))
    l4=Label(f2,image=img3)
    l4.place(relx=0.74,rely=0.15)
    img4=ImageTk.PhotoImage(Image.open('womenfoot5.jpg'))
    l5=Label(f2,image=img4)
    l5.place(relx=0.08,rely=0.6)
    img5=ImageTk.PhotoImage(Image.open('womenfoot6.jpg'))
    l6=Label(f2,image=img5)
    l6.place(relx=0.33,rely=0.6)
    img6=ImageTk.PhotoImage(Image.open('womenfoot7.jpg'))
    l6=Label(f2,image=img6)
    l6.place(relx=0.51,rely=0.6)
    img7=ImageTk.PhotoImage(Image.open('womenfoot8.jpg'))
    l6=Label(f2,image=img7)
    l6.place(relx=0.73,rely=0.6)
    
    b=Button(root,text="Flats",fg="black",bg="skyblue",font=label_font)
    b.place(relx=0.24,rely=0.55)

    b1=Button(root,text="Black Heels",fg="black",bg="skyblue",font=label_font)
    b1.place(relx=0.57,rely=0.46)

    b2=Button(root,text="High Heels",fg="black",bg="skyblue",font=label_font)
    b2.place(relx=0.42,rely=0.46)

    b3=Button(root,text="Stone Flat",fg="black",bg="skyblue",font=label_font)
    b3.place(relx=0.75,rely=0.46)

    b4=Button(root,text="Heels",fg="black",bg="skyblue",font=label_font)
    b4.place(relx=0.24,rely=0.92)
    
    b5=Button(root,text="flat sandals",fg="black",bg="skyblue",font=label_font)
    b5.place(relx=0.57,rely=0.88)
    
    b6=Button(root,text="sandals",fg="black",bg="skyblue",font=label_font,command=lambda:womenfoot(root))
    b6.place(relx=0.42,rely=0.88)
    b7=Button(root,text="pink sandals",fg="black",bg="skyblue",font=label_font)
    b7.place(relx=0.72,rely=0.88)
    label_font1=font.Font(weight="bold",family="calibri",size=17)
    lbl1=Label(root,text="Rs.250",fg="black",bg="pink",font=label_font1)
    lbl1.place(relx=0.28,rely=0.55)
    lbl2=Label(root,text="Rs.300",fg="black",bg="pink",font=label_font1)
    lbl2.place(relx=0.43,rely=0.51)
    lbl3=Label(root,text="Rs.350",fg="black",bg="pink",font=label_font1)
    lbl3.place(relx=0.75,rely=0.51)
    lbl4=Label(root,text="Rs.450",fg="black",bg="pink",font=label_font1)
    lbl4.place(relx=0.58,rely=0.93)
    lbl5=Label(root,text="Rs.500",fg="black",bg="pink",font=label_font1)
    lbl5.place(relx=0.28,rely=0.92)
    lbl6=Label(root,text="Rs.570",fg="black",bg="pink",font=label_font1)
    lbl6.place(relx=0.42,rely=0.93)
    lbl7=Label(root,text="Rs.650",fg="black",bg="pink",font=label_font1)
    lbl7.place(relx=0.58,rely=0.51)
    lbl8=Label(root,text="Rs.700",fg="black",bg="pink",font=label_font1)
    lbl8.place(relx=0.73,rely=0.93)  
    f1.pack()    
    root.mainloop()

def women_access(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=12) 
    img8=ImageTk.PhotoImage(Image.open('background.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.00)
    f2=Frame(root,height=710,width=1000,bg="pink")
    f2.place(relx=0.15,rely=0.05)
    label_fontt=font.Font(weight="bold",family="calibri",size=25) 
    label=Label(f2,text="WOMEN'S ACCESSORIES",bg="pink",fg="black",font=label_fontt)
    label.place(relx=0.35,rely=0.05) 
    img=ImageTk.PhotoImage(Image.open('womenaccess11.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.08,rely=0.15)
    img1=ImageTk.PhotoImage(Image.open('womenaccess2.jpg'))
    l2=Label(f2,image=img1)
    l2.place(relx=0.31,rely=0.15)
    img2=ImageTk.PhotoImage(Image.open('womenaccess3.jpg'))
    l3=Label(f2,image=img2)
    l3.place(relx=0.53,rely=0.15)
    img3=ImageTk.PhotoImage(Image.open('womenaccess4.jpg'))
    l4=Label(f2,image=img3)
    l4.place(relx=0.75,rely=0.15)
    img4=ImageTk.PhotoImage(Image.open('womenaccess10.jpg'))
    l5=Label(f2,image=img4)
    l5.place(relx=0.08,rely=0.6)
    img5=ImageTk.PhotoImage(Image.open('womenaccess6.jpg'))
    l6=Label(f2,image=img5)
    l6.place(relx=0.33,rely=0.6)
    img6=ImageTk.PhotoImage(Image.open('womenaccess7.jpg'))
    l6=Label(f2,image=img6)
    l6.place(relx=0.51,rely=0.6)
    img7=ImageTk.PhotoImage(Image.open('womenaccess9.jpg'))
    l6=Label(f2,image=img7)
    l6.place(relx=0.71,rely=0.6)
     
    b=Button(root,text="women watch",fg="black",bg="skyblue",font=label_font)
    b.place(relx=0.25,rely=0.46)

    b1=Button(root,text="stone earing",fg="black",bg="skyblue",font=label_font)
    b1.place(relx=0.57,rely=0.46)

    b2=Button(root,text="stone studs",fg="black",bg="skyblue",font=label_font)
    b2.place(relx=0.41,rely=0.46)

    b3=Button(root,text="Neck sets",fg="black",bg="skyblue",font=label_font)
    b3.place(relx=0.74,rely=0.46)

    b4=Button(root,text="simple wallet",fg="black",bg="skyblue",font=label_font)
    b4.place(relx=0.25,rely=0.87)
    
    b5=Button(root,text="Jewels sets",fg="black",bg="skyblue",font=label_font,command=lambda:womenaccess(root))
    b5.place(relx=0.55,rely=0.87)
    
    b6=Button(root,text="Trendy sets",fg="black",bg="skyblue",font=label_font)
    b6.place(relx=0.41,rely=0.87)
    b7=Button(root,text="Trendy watches",fg="black",bg="skyblue",font=label_font)
    b7.place(relx=0.73,rely=0.87)
    label_font1=font.Font(weight="bold",family="calibri",size=17)
    lbl1=Label(root,text="Rs.250",fg="black",bg="pink",font=label_font1)
    lbl1.place(relx=0.26,rely=0.51)
    lbl2=Label(root,text="Rs.300",fg="black",bg="pink",font=label_font1)
    lbl2.place(relx=0.41,rely=0.51)
    lbl3=Label(root,text="Rs.350",fg="black",bg="pink",font=label_font1)
    lbl3.place(relx=0.75,rely=0.51)
    lbl4=Label(root,text="Rs.450",fg="black",bg="pink",font=label_font1)
    lbl4.place(relx=0.56,rely=0.92)
    lbl5=Label(root,text="Rs.500",fg="black",bg="pink",font=label_font1)
    lbl5.place(relx=0.26,rely=0.92)
    lbl6=Label(root,text="Rs.570",fg="black",bg="pink",font=label_font1)
    lbl6.place(relx=0.41,rely=0.92)
    lbl7=Label(root,text="Rs.650",fg="black",bg="pink",font=label_font1)
    lbl7.place(relx=0.57,rely=0.51)
    lbl8=Label(root,text="Rs.700",fg="black",bg="pink",font=label_font1)
    lbl8.place(relx=0.75,rely=0.92)  
    f1.pack()  
    root.mainloop()

   
   
def home_kid_store(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f=Frame(root,height=1500,width=1500,bg="gray")
    label_font=font.Font(weight="bold",family="Times New Roman",size=20) 
    img8=ImageTk.PhotoImage(Image.open('onlineshop4.jpg'))
    ll=Label(f,image=img8)
    ll.place(relx=0.0,rely=0.00) 
    label=Label(root,text="HOME'S STORE",font=label_font,bg="orange")
    label.place(relx=0.21,rely=0.1)
    label1=Label(root,text="KID'S STORE",font=label_font,bg="orange")
    label1.place(relx=0.66,rely=0.1)
    f1=Frame(root,height=530,width=500,bg="skyblue")
    f1.place(relx=0.1,rely=0.2)
    img=ImageTk.PhotoImage(Image.open('furnit.jpg'))
    l1=Label(f1,image=img)
    l1.place(relx=0.13,rely=0.06)
    img1=ImageTk.PhotoImage(Image.open('decor1.jpg'))
    l2=Label(f1,image=img1)
    l2.place(relx=0.6,rely=0.06)
    img2=ImageTk.PhotoImage(Image.open('dining.jpg'))
    l3=Label(f1,image=img2)
    l3.place(relx=0.13,rely=0.53)
    img3=ImageTk.PhotoImage(Image.open('cook.jpg'))
    l4=Label(f1,image=img3)
    l4.place( relx=0.57,rely=0.5)
    b1=Button(f1,text="Furnishing",font=label_font,bg="purple",fg="yellow")
    b1.place(relx=0.19,rely=0.37)
    b2=Button(f1,text="Home Decor",font=label_font,bg="purple",fg="yellow")
    b2.place(relx=0.6,rely=0.37)
    b3=Button(f1,text="Dining",font=label_font,bg="purple",fg="yellow")
    b3.place(relx=0.65,rely=0.86)
    b4=Button(f1,text="CookWare",font=label_font,bg="purple",fg="yellow")
    b4.place(relx=0.2,rely=0.86)
    f.pack()
    f2=Frame(root,width=500,height=530,bg="skyblue")
    img4=ImageTk.PhotoImage(Image.open('kids1.jpg'))
    lbl1=Label(f2,image=img4)
    lbl1.place(relx=0.15,rely=0.04)
    img5=ImageTk.PhotoImage(Image.open('toys.jpg'))
    lbl2=Label(f2,image=img5)
    lbl2.place(relx=0.45,rely=0.07)
    img6=ImageTk.PhotoImage(Image.open('kid health.jpg'))
    lbl3=Label(f2,image=img6)
    lbl3.place(relx=0.15,rely=0.55)
    img7=ImageTk.PhotoImage(Image.open('kid acces.jpg'))
    lbl4=Label(f2,image=img7)
    lbl4.place(relx=0.55,rely=0.52)
    btn1=Button(f2,text="Clothess",font=label_font,bg="purple",fg="yellow")
    btn1.place(relx=0.2,rely=0.44)
    btn2=Button(f2,text="Toys",font=label_font,bg="purple",fg="yellow")
    btn2.place(relx=0.61,rely=0.37)
    btn3=Button(f2,text="Accessories",font=label_font,bg="purple",fg="yellow")
    btn3.place(relx=0.58,rely=0.87)
    btn4=Button(f2,text="Health Care",font=label_font,bg="purple",fg="yellow")
    btn4.place(relx=0.18,rely=0.87)
    btn5=Button(root,text="Back",font=label_font,bg="orange",fg="black",command=lambda:start(root))
    btn5.place(relx=0.86,rely=0.9)
    f2.place(relx=0.55,rely=0.2)
    root.mainloop()
 
  
def Top_Wear(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=12)
    img8=ImageTk.PhotoImage(Image.open('background.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.00)  
    f2=Frame(root,height=720,width=1000,bg="skyblue")
    f2.place(relx=0.15,rely=0.05)
    label_fontt=font.Font(weight="bold",family="calibri",size=25) 
    label=Label(f2,text="TOP WEAR COLLECTION",bg="skyblue",fg="black",font=label_fontt)
    label.place(relx=0.35,rely=0.05)  
    img=ImageTk.PhotoImage(Image.open('top1.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.13,rely=0.15)
    img1=ImageTk.PhotoImage(Image.open('top2.jpg'))
    l2=Label(f2,image=img1)
    l2.place(relx=0.33,rely=0.15)
    img2=ImageTk.PhotoImage(Image.open('top3.jpg'))
    l3=Label(f2,image=img2)
    l3.place(relx=0.54,rely=0.15)
    img3=ImageTk.PhotoImage(Image.open('top4.jpg'))
    l4=Label(f2,image=img3)
    l4.place(relx=0.73,rely=0.15)
    img4=ImageTk.PhotoImage(Image.open('top5.jpg'))
    l5=Label(f2,image=img4)
    l5.place(relx=0.13,rely=0.6)
    img5=ImageTk.PhotoImage(Image.open('top6.jpg'))
    l6=Label(f2,image=img5)
    l6.place(relx=0.33,rely=0.6)
    img6=ImageTk.PhotoImage(Image.open('top8.jpg'))
    l6=Label(f2,image=img6)
    l6.place(relx=0.57,rely=0.6)
    img7=ImageTk.PhotoImage(Image.open('top7.jpg'))
    l6=Label(f2,image=img7)
    l6.place(relx=0.73,rely=0.6)
    
    b=Button(root,text="Black coat ",fg="black",bg="pink",font=label_font,command=lambda:mentop(root))
    b.place(relx=0.26,rely=0.46)

    b1=Button(root,text="Tshirt",fg="black",bg="pink",font=label_font)
    b1.place(relx=0.58,rely=0.46)

    b2=Button(root,text="Blue coat",fg="black",bg="pink",font=label_font)
    b2.place(relx=0.41,rely=0.46)

    b3=Button(root,text="Blue Tshirt",fg="black",bg="pink",font=label_font)
    b3.place(relx=0.71,rely=0.46)

    b4=Button(root,text="Ash Tshirt",fg="black",bg="pink",font=label_font)
    b4.place(relx=0.27,rely=0.88)
    
    b5=Button(root,text="Swetter",fg="black",bg="pink",font=label_font)
    b5.place(relx=0.58,rely=0.88)
    
    b6=Button(root,text="Printed Tshirt",fg="black",bg="pink",font=label_font)
    b6.place(relx=0.43,rely=0.88)
    b7=Button(root,text="Black swetter",fg="black",bg="pink",font=label_font)
    b7.place(relx=0.71,rely=0.88)
    label_font1=font.Font(weight="bold",family="calibri",size=17)
    lbl1=Label(root,text="Rs.250",fg="black",bg="skyblue",font=label_font1)
    lbl1.place(relx=0.26,rely=0.51)
    lbl2=Label(root,text="Rs.300",fg="black",bg="skyblue",font=label_font1)
    lbl2.place(relx=0.41,rely=0.51)
    lbl3=Label(root,text="Rs.350",fg="black",bg="skyblue",font=label_font1)
    lbl3.place(relx=0.71,rely=0.51)
    lbl4=Label(root,text="Rs.450",fg="black",bg="skyblue",font=label_font1)
    lbl4.place(relx=0.58,rely=0.93)
    lbl5=Label(root,text="Rs.500",fg="black",bg="skyblue",font=label_font1)
    lbl5.place(relx=0.27,rely=0.93)
    lbl6=Label(root,text="Rs.570",fg="black",bg="skyblue",font=label_font1)
    lbl6.place(relx=0.44,rely=0.93)
    lbl7=Label(root,text="Rs.650",fg="black",bg="skyblue",font=label_font1)
    lbl7.place(relx=0.57,rely=0.51)
    lbl8=Label(root,text="Rs.700",fg="black",bg="skyblue",font=label_font1)
    lbl8.place(relx=0.72,rely=0.93)


    
    f1.pack()
    
    root.mainloop()
     
def Bottom_Wear(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=12) 
    img8=ImageTk.PhotoImage(Image.open('onlineshop4.jpg'))
    ll=Label(f1,image=img8)
    ll.place(relx=0.0,rely=0.00) 
    f2=Frame(root,height=710,width=1000,bg="skyblue")
    f2.place(relx=0.15,rely=0.05)
    label_fontt=font.Font(weight="bold",family="calibri",size=25) 
    label=Label(f2,text="BOTTOM WEAR COLLECTIONS",bg="skyblue",fg="black",font=label_fontt)
    label.place(relx=0.35,rely=0.05)   
    img=ImageTk.PhotoImage(Image.open('bottom1.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.13,rely=0.15)
    img1=ImageTk.PhotoImage(Image.open('bottom2.jpg'))
    l2=Label(f2,image=img1)
    l2.place(relx=0.37,rely=0.15)
    img2=ImageTk.PhotoImage(Image.open('bottom3.jpg'))
    l3=Label(f2,image=img2)
    l3.place(relx=0.57,rely=0.15)
    img3=ImageTk.PhotoImage(Image.open('bottom8.jpg'))
    l4=Label(f2,image=img3)
    l4.place(relx=0.77,rely=0.15)
    img4=ImageTk.PhotoImage(Image.open('bottom5.jpg'))
    l5=Label(f2,image=img4)
    l5.place(relx=0.13,rely=0.6)
    img5=ImageTk.PhotoImage(Image.open('bottom6.jpg'))
    l6=Label(f2,image=img5)
    l6.place(relx=0.37,rely=0.6)
    img6=ImageTk.PhotoImage(Image.open('bottom4.jpg'))
    l6=Label(f2,image=img6)
    l6.place(relx=0.57,rely=0.6)
    img7=ImageTk.PhotoImage(Image.open('bottom7.jpg'))
    l6=Label(f2,image=img7)
    l6.place(relx=0.77,rely=0.6)
     
    b=Button(root,text="Lower sets",fg="black",bg="pink",font=label_font,command=lambda:menbottom(root))
    b.place(relx=0.29,rely=0.46)

    b1=Button(root,text="Formal Pant",fg="black",bg="pink",font=label_font)
    b1.place(relx=0.58,rely=0.46)

    b2=Button(root,text="Printed pant",fg="black",bg="pink",font=label_font)
    b2.place(relx=0.44,rely=0.46)

    b3=Button(root,text="shorts",fg="black",bg="pink",font=label_font)
    b3.place(relx=0.77,rely=0.46)

    b4=Button(root,text="Night pants",fg="black",bg="pink",font=label_font)
    b4.place(relx=0.29,rely=0.87)
    
    b5=Button(root,text="printed pant",fg="black",bg="pink",font=label_font)
    b5.place(relx=0.59,rely=0.87)
    
    b6=Button(root,text="shorts",fg="black",bg="pink",font=label_font)
    b6.place(relx=0.46,rely=0.87)
    b7=Button(root,text="prined shorts",fg="black",bg="pink",font=label_font)
    b7.place(relx=0.75,rely=0.87)
    label_font1=font.Font(weight="bold",family="calibri",size=17)
    lbl1=Label(root,text="Rs.250",fg="black",bg="skyblue",font=label_font1)
    lbl1.place(relx=0.3,rely=0.51)
    lbl2=Label(root,text="Rs.300",fg="black",bg="skyblue",font=label_font1)
    lbl2.place(relx=0.45,rely=0.51)
    lbl3=Label(root,text="Rs.350",fg="black",bg="skyblue",font=label_font1)
    lbl3.place(relx=0.76,rely=0.51)
    lbl4=Label(root,text="Rs.450",fg="black",bg="skyblue",font=label_font1)
    lbl4.place(relx=0.6,rely=0.92)
    lbl5=Label(root,text="Rs.500",fg="black",bg="skyblue",font=label_font1)
    lbl5.place(relx=0.3,rely=0.92)
    lbl6=Label(root,text="Rs.570",fg="black",bg="skyblue",font=label_font1)
    lbl6.place(relx=0.45,rely=0.92)
    lbl7=Label(root,text="Rs.650",fg="black",bg="skyblue",font=label_font1)
    lbl7.place(relx=0.59,rely=0.51)
    lbl8=Label(root,text="Rs.700",fg="black",bg="skyblue",font=label_font1)
    lbl8.place(relx=0.76,rely=0.92)


    f1.pack()
    
    root.mainloop()
        
def access(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=12) 
    f2=Frame(root,height=710,width=1000,bg="skyblue")
    f2.place(relx=0.15,rely=0.05)
    label_fontt=font.Font(weight="bold",family="calibri",size=25) 
    label=Label(f2,text="MEN'S ACCESSORIES",bg="skyblue",fg="black",font=label_fontt)
    label.place(relx=0.35,rely=0.05) 
    img=ImageTk.PhotoImage(Image.open('menaccess1.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.11,rely=0.15)
    img1=ImageTk.PhotoImage(Image.open('menaccess2.jpg'))
    l2=Label(f2,image=img1)
    l2.place(relx=0.41,rely=0.15)
    img2=ImageTk.PhotoImage(Image.open('menaccess3.jpg'))
    l3=Label(f2,image=img2)
    l3.place(relx=0.69,rely=0.15)
    img3=ImageTk.PhotoImage(Image.open('menaccess4.jpg'))
    l4=Label(f2,image=img3)
    l4.place(relx=0.57,rely=0.57)
    img4=ImageTk.PhotoImage(Image.open('menaccess5.jpg'))
    l5=Label(f2,image=img4)
    l5.place(relx=0.11,rely=0.57)
    img5=ImageTk.PhotoImage(Image.open('menaccess6.jpg'))
    l6=Label(f2,image=img5)
    l6.place(relx=0.33,rely=0.57)
    img6=ImageTk.PhotoImage(Image.open('menaccess7.jpg'))
    l6=Label(f2,image=img6)
    l6.place(relx=0.77,rely=0.57)
    img7=ImageTk.PhotoImage(Image.open('menaccess8.jpg'))
    l6=Label(f2,image=img7)
    l6.place(relx=0.75,rely=0.72)
     
    b=Button(root,text="Trendy watch",fg="black",bg="pink",font=label_font,command=lambda:menaccess(root))
    b.place(relx=0.27,rely=0.43)

    b1=Button(root,text="silver watch",fg="black",bg="pink",font=label_font)
    b1.place(relx=0.5,rely=0.43)


    b3=Button(root,text="Accessories",fg="black",bg="pink",font=label_font)
    b3.place(relx=0.7,rely=0.43)

    b4=Button(root,text="wallet",fg="black",bg="pink",font=label_font)
    b4.place(relx=0.29,rely=0.86)
    
    b5=Button(root,text="Trendy wallet",fg="black",bg="pink",font=label_font)
    b5.place(relx=0.58,rely=0.86)
    
    b6=Button(root,text="watch",fg="black",bg="pink",font=label_font)
    b6.place(relx=0.45,rely=0.86)
    b7=Button(root,text="sunglasses",fg="black",bg="pink",font=label_font)
    b7.place(relx=0.76,rely=0.86)
    label_font1=font.Font(weight="bold",family="calibri",size=17)
    lbl1=Label(root,text="Rs.250",fg="black",bg="pink",font=label_font1)
    lbl1.place(relx=0.28,rely=0.48)
    lbl2=Label(root,text="Rs.300",fg="black",bg="pink",font=label_font1)
    lbl2.place(relx=0.51,rely=0.48)
    lbl3=Label(root,text="Rs.350",fg="black",bg="pink",font=label_font1)
    lbl3.place(relx=0.71,rely=0.48)
    lbl4=Label(root,text="Rs.450",fg="black",bg="pink",font=label_font1)
    lbl4.place(relx=0.59,rely=0.91)
    lbl5=Label(root,text="Rs.500",fg="black",bg="pink",font=label_font1)
    lbl5.place(relx=0.29,rely=0.91)
    lbl6=Label(root,text="Rs.570",fg="black",bg="pink",font=label_font1)
    lbl6.place(relx=0.44,rely=0.91)
    lbl8=Label(root,text="Rs.700",fg="black",bg="pink",font=label_font1)
    lbl8.place(relx=0.76,rely=0.91)
    f1.pack()  
    root.mainloop()       
def foot(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f1=Frame(root,height=1500,width=1500,bg="blue")
    label_font=font.Font(weight="bold",family="Times New Roman",size=12) 
    f2=Frame(root,height=710,width=1000,bg="skyblue")
    f2.place(relx=0.15,rely=0.05)
    label_fontt=font.Font(weight="bold",family="calibri",size=25) 
    label=Label(f2,text="MEN'S FOOT WEAR",bg="skyblue",fg="black",font=label_fontt)
    label.place(relx=0.35,rely=0.05)   
    img=ImageTk.PhotoImage(Image.open('footwear1.jpg'))
    l1=Label(f2,image=img)
    l1.place(relx=0.08,rely=0.15)
    img1=ImageTk.PhotoImage(Image.open('footwear2.jpg'))
    l2=Label(f2,image=img1)
    l2.place(relx=0.35,rely=0.15)
    img2=ImageTk.PhotoImage(Image.open('footwear3.jpg'))
    l3=Label(f2,image=img2)
    l3.place(relx=0.57,rely=0.15)
    img3=ImageTk.PhotoImage(Image.open('footwear4.jpg'))
    l4=Label(f2,image=img3)
    l4.place(relx=0.55,rely=0.59)
    img4=ImageTk.PhotoImage(Image.open('footwear5.jpg'))
    l5=Label(f2,image=img4)
    l5.place(relx=0.08,rely=0.59)
    img5=ImageTk.PhotoImage(Image.open('footwear6.jpg'))
    l6=Label(f2,image=img5)
    l6.place(relx=0.32,rely=0.59)
    img6=ImageTk.PhotoImage(Image.open('footwear7.jpg'))
    l7=Label(f2,image=img6)
    l7.place(relx=0.81,rely=0.59)
    img7=ImageTk.PhotoImage(Image.open('footwear8.jpg'))
    l8=Label(f2,image=img7)
    l8.place(relx=0.80,rely=0.15)
     
    b=Button(root,text="Black Shoes",fg="black",bg="pink",font=label_font,command=lambda:menfoot(root))
    b.place(relx=0.26,rely=0.46)

    b1=Button(root,text="Blue Shoes",fg="black",bg="pink",font=label_font)
    b1.place(relx=0.6,rely=0.46)

    b2=Button(root,text="Formal Shoes",fg="black",bg="pink",font=label_font)
    b2.place(relx=0.44,rely=0.46)

    b3=Button(root,text="Sports Shoes",fg="black",bg="pink",font=label_font)
    b3.place(relx=0.77,rely=0.46)

    b4=Button(root,text="Cut Shoes",fg="black",bg="pink",font=label_font)
    b4.place(relx=0.26,rely=0.87)
    
    b5=Button(root,text="Color Cut Shoes",fg="black",bg="pink",font=label_font)
    b5.place(relx=0.6,rely=0.87)
    
    b6=Button(root,text="Trendy Cut Shoes",fg="black",bg="pink",font=label_font)
    b6.place(relx=0.42,rely=0.87)
    b7=Button(root,text="Shoes",fg="black",bg="pink",font=label_font)
    b7.place(relx=0.78,rely=0.87)
    label_font1=font.Font(weight="bold",family="calibri",size=17)
    lbl1=Label(root,text="Rs.250",fg="black",bg="skyblue",font=label_font1)
    lbl1.place(relx=0.26,rely=0.51)
    lbl2=Label(root,text="Rs.300",fg="black",bg="skyblue",font=label_font1)
    lbl2.place(relx=0.45,rely=0.51)
    lbl3=Label(root,text="Rs.350",fg="black",bg="skyblue",font=label_font1)
    lbl3.place(relx=0.78,rely=0.51)
    lbl4=Label(root,text="Rs.450",fg="black",bg="skyblue",font=label_font1)
    lbl4.place(relx=0.62,rely=0.92)
    lbl5=Label(root,text="Rs.500",fg="black",bg="skyblue",font=label_font1)
    lbl5.place(relx=0.26,rely=0.92)
    lbl6=Label(root,text="Rs.570",fg="black",bg="skyblue",font=label_font1)
    lbl6.place(relx=0.44,rely=0.92)
    lbl7=Label(root,text="Rs.650",fg="black",bg="skyblue",font=label_font1)
    lbl7.place(relx=0.6,rely=0.51)
    lbl8=Label(root,text="Rs.700",fg="black",bg="skyblue",font=label_font1)
    lbl8.place(relx=0.77,rely=0.92)
    f1.pack()
    root.mainloop()


def women_men_store(root):
    root.destroy()
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f=Frame(root,height=1500,width=1500,bg="light green")
    label_font=font.Font(weight="bold",family="Times New Roman",size=20) 
    img8=ImageTk.PhotoImage(Image.open('onlineshop4.jpg'))
    ll=Label(f,image=img8)
    ll.place(relx=0.0,rely=0.00)

    label=Label(root,text="WOMEN'S STORE",font=label_font,bg="orange")
    label.place(relx=0.22,rely=0.1)
    label=Label(root,text="MEN'S STORE",font=label_font,bg="orange")
    label.place(relx=0.63,rely=0.1)
    

    f1=Frame(root,height=520,width=500,bg="skyblue")
    f1.place(relx=0.1,rely=0.2)
    f.pack() 
    
    f2=Frame(root,height=520,width=500,bg="skyblue")
    f2.place(relx=0.54,rely=0.2)
    f.pack() 

    img=ImageTk.PhotoImage(Image.open('kurtis.jpg'))
    l1=Label(f1,image=img)
    l1.place(relx=0.17,rely=0.08)
    img1=ImageTk.PhotoImage(Image.open('saree4.jpg'))
    l2=Label(f1,image=img1)
    l2.place(relx=0.58,rely=0.08)
    img2=ImageTk.PhotoImage(Image.open('womenaccess1.jpg'))
    l3=Label(f1,image=img2)
    l3.place(relx=0.15,rely=0.56)
    img3=ImageTk.PhotoImage(Image.open('foot2.jpg'))
    l5=Label(f1,image=img3)
    l5.place(relx=0.70,rely=0.56)

    b1=Button(root,text="Kurtisss",font=label_font,bg="purple",fg="yellow",command=lambda:kurtis(root))
    b1.place(relx=0.16,rely=0.47)
    b2=Button(root,text="Sarees",font=label_font,bg="purple",fg="yellow",command=lambda:sarees(root))
    b2.place(relx=0.32,rely=0.47)
    b3=Button(root,text="Accessories",font=label_font,bg="purple",fg="yellow",command=lambda:women_access(root))
    b3.place(relx=0.18,rely=0.79)
    b6=Button(root,text="Foot wear",font=label_font,bg="purple",fg="yellow",command=lambda:women_foot(root))
    b6.place(relx=0.36,rely=0.79)

    img4=ImageTk.PhotoImage(Image.open('tshi.jpg'))
    l1=Label(f2,image=img4)
    l1.place(relx=0.17,rely=0.08)
    img5=ImageTk.PhotoImage(Image.open('jeans.jpg'))
    l2=Label(f2,image=img5)
    l2.place(relx=0.58,rely=0.08)
    img6=ImageTk.PhotoImage(Image.open('menaccesss.jpg'))
    l3=Label(f2,image=img6)
    l3.place(relx=0.15,rely=0.56)
    img7=ImageTk.PhotoImage(Image.open('foot.jpg'))
    l5=Label(f2,image=img7)
    l5.place(relx=0.70,rely=0.56)

    b1=Button(root,text="Top Wear",font=label_font,bg="purple",fg="yellow",command=lambda:Top_Wear(root))
    b1.place(relx=0.58,rely=0.47)
    b2=Button(root,text="Bottom Wear",font=label_font,bg="purple",fg="yellow",command=lambda:Bottom_Wear(root))
    b2.place(relx=0.73,rely=0.47)
    b3=Button(root,text="Accessories",font=label_font,bg="purple",fg="yellow",command=lambda:access(root))
    b3.place(relx=0.63,rely=0.79)
    b5=Button(root,text="Foot Wear",font=label_font,bg="purple",fg="yellow",command=lambda:foot(root))
    b5.place(relx=0.78,rely=0.79)
    b6=Button(root,text="Back",font=label_font,bg="orange",fg="black",command=lambda:start(root))
    b6.place(relx=0.86,rely=0.9)
    f.pack()
    root.mainloop()


def home():
    root=Tk()
    root.geometry("500x500")
    root.attributes('-fullscreen',True)
    f=Frame(root,width=1500,height=50,bg="purple")
    f.pack()
    label_font=font.Font(weight="bold",family="Calibri",size=30)
    l=Label(root,text="ONLINE SHOPPING",bg="purple",fg="yellow",font=label_font)
    l.place(relx=0.4,rely=0.0)
    f1=Frame(root,width=1500,height=1500,bg="purple")
    f1.pack()
    img12=ImageTk.PhotoImage(Image.open('shops.jpg'))
    l1=Label(f1,image=img12)
    l1.place(relx=0.0,rely=0.00)
    label_font1=font.Font(weight="bold",family="Calibri",size=20)
    b=Button(f1,text="CUSTOMER REGISTRATION",bg="purple",fg="yellow",font=label_font1,command=lambda:cust_regis(root))
    b.place(relx=0.03,rely=0.2)
    b=Button(f1,text="CUSTOMER LOGIN",bg="purple",fg="yellow",font=label_font1,command=lambda:cust_login(root))
    b.place(relx=0.03,rely=0.4)

    b=Button(f1,text="CLOSE",bg="purple",fg="yellow",font=label_font1,command=lambda:exit())
    b.place(relx=0.03,rely=0.6)
    root.mainloop()
home()
